
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- task: Docker@2
  inputs:
    containerRegistry: $(dockerHub)
    repository: $(imageName)
    command: 'buildAndPush'
    tags: |
      latest
      $(Build.BuildNumber) 
    Dockerfile: '**/Dockerfile-run'

- task: HelmDeploy@0
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceConnection: 'service-kubernetes'
    command: 'upgrade'
    chartType: 'FilePath'
    chartPath: 'chart/'
    install: false
    recreate: true