trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- task: Docker@2
  inputs:
    repository: casestudy
    command: 'buildAndPush'
    tags: |
      latest
      $(Build.BuildNumber) 
    Dockerfile: '**/Dockerfile-run'